export const BOTTOM_TOOLBAR_BUTTONS = {
    DOWNLOAD: 'DOWNLOAD',
    REQUEST_REVIEW: 'REQUEST_REVIEW',
    ADD_ITEM: 'ADD_ITEM'
};

export const STATUS = {
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    PENDING: 'PENDING',
    ORDERED: 'ORDERED',
    BACK_ORDERED: 'BACK_ORDERED',
    PARTIAL_RECEIPT: 'PARTIAL_RECEIPT'
};

export const DEPARTMENT = {
    EXTRACTIONS: 'EXTRACTIONS',
    MASS_SPEC: 'MASS_SPEC',
    RD: 'RD',
    SCREENING: 'SCREENING',
    SHIPPING: 'SHIPPING',
    PROCESSING_LAB: 'PROCESSING_LAB',
    QC_INTERNAL_STANDARDS: 'QC_INTERNAL_STANDARDS',
    QC_QA: 'QC_QA',
    STORE_ROOM: 'STORE_ROOM',
    GENERAL: 'GENERAL',
    OFFICE_SUPPLY: 'OFFICE_SUPPLY'
};

export const CONFIRMATION = {
    WAITING: 'WAITING',
    COMPLETE: 'COMPLETE'
};



export const CATEGORY = {
    GC: 'GC',
    LC: 'LC',
    COLUMNS: 'COLUMNS',
    GENERAL: 'GENERAL',
    GASES: 'GASES',
    SOLVENTS: 'SOLVENTS',
    LDTD: 'LDTD',
    SCIEX: 'SCIEX'
};

export const ROLE = {
    ADMINISTRATION: 'ADMINISTRATION',
    USER: 'USER'
};

export const PERMISSION = {
    ALLOW: 'ALLOW',
    DENY: 'DENY'
};
